deployment:
  tasks:
    - echo "🚀 Starting deployment to public_html..."

    # Define destination path
    - export DEPLOYPATH=/home4/futureconnect/public_html

    # Optional: Clean public_html before copying (dangerous if you have custom files there)
    - echo "🧹 Cleaning old files in public_html..."
    - rm -rf $DEPLOYPATH/*

    # Copy all files except .git and .cpanel.yml to public_html
    - echo "📦 Copying new files to public_html..."
    - rsync -av --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH

    - echo "✅ Deployment complete!"
