name: Deploy to cPanel via FTPS

on:
  push:
    branches:
      - main  # Adjust if you're using a different deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.futureconnect.rw
          username: ${{ secrets.FTP_USERNAME }}        # Set this secret in GitHub
          password: ${{ secrets.FTP_PASSWORD }}        # Set this secret in GitHub
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}    # e.g., /public_html/
          local-dir: ./                                # Root directory of your HTML/CSS/JS
          protocol: ftps
